version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.7"

sphinx:
  fail_on_warning: true

python:
  install:
    - requirements: ./docs/source/requirements.txt
    - method: pip
      path: .